apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: ubuntu
    image: learnk8s/advanced-networking
    command: ["nping", "--echo-server=public", "--interface=eth0"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - name: ubuntu
    image: learnk8s/advanced-networking
    command: ["nping", "--echo-server=public", "--interface=eth0"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
  - name: ubuntu
    image: learnk8s/advanced-networking
    command: ["nping", "--echo-server=public", "--interface=eth0"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
spec:
  containers:
  - name: ubuntu
    image: learnk8s/advanced-networking
    command: ["nping", "--echo-server=public", "--interface=eth0"]
